config/routes.rb
Rails.application.routes.draw do
  resources :enologist_magazines
  resources :magazines
  resources :enologists
  devise_for :users
  resources :strains
  resources :wines
  resources :enologist_wines
  

  root to: 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enologist.rb
class Enologist < ApplicationRecord
    has_many :enologist_wines
    has_many :wines, through: :enologist_wines, dependent: :destroy

    has_many :enologist_magazines
    has_many :magazines, through: :enologist_magazines, dependent: :destroy


    accepts_nested_attributes_for :enologist_wines, reject_if: ->(attributes){ attributes['wine_id'].blank? || attributes['score'].blank? }, allow_destroy: true
    
    def to_s
        name
    end
    
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: %i[ show edit update destroy ]

  # GET /enologists or /enologists.json
  def index
    @enologists = Enologist.all
    @enologists = Enologist.order(age: :desc)
    
  end

  # GET /enologists/1 or /enologists/1.json
  def show
  end

  # GET /enologists/new
  def new
    @enologist = Enologist.new
    #@wines = Wines.pluck(:name, :id)  #repasar, los botones de build, es para dar mas de una seleccion
    @enologist.enologist_wines.build
    @enologist.enologist_wines.build
    @enologist.enologist_wines.build
    3.times { @enologist.enologist_magazines.build }
  end

  # GET /enologists/1/edit
  def edit
    #@wines = Wines.name.pluck(:name, :id)  #repasar, los botones de build, es para dar mas de una seleccion
    3.times { @enologist.enologist_wines.build }
    3.times { @enologist.enologist_magazines.build }
  end

  # POST /enologists or /enologists.json
  def create
    @enologist = Enologist.new(enologist_params)

    respond_to do |format|
      if @enologist.save
        format.html { redirect_to @enologist, notice: "Enologist was successfully created." }
        format.json { render :show, status: :created, location: @enologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologists/1 or /enologists/1.json
  def update
    respond_to do |format|
      if @enologist.update(enologist_params)
        format.html { redirect_to @enologist, notice: "Enologist was successfully updated." }
        format.json { render :show, status: :ok, location: @enologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologists/1 or /enologists/1.json
  def destroy
    @enologist.destroy
    respond_to do |format|
      format.html { redirect_to enologists_url, notice: "Enologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:name, :age, :nationality, enologist_wines_attributes: [:id, :wine_id, :score, :_destroy], enologist_magazines_attribute: [:id, :editor, :writer, :reviewer, :magazine_id, :_destroy])
    end
end

app/helpers/enologists_helper.rb
module EnologistsHelper
    def sort_magazines(enologist_magazines)
        enologist_magazines.map { |em| [em.magazine.name]}
                           .sort
                           .join(',')
    end

    def sort_job(enologist_magazines)
        enologist_magazines.map { |em| [ em.editor, em.writer, em.reviewer]}
                           .sort
                           .join(',')
    end
end

app/views/enologists/_form.html.erb
<%= form_with(model: enologist) do |form| %>
  <% if enologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
        <% enologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <%= form.fields_for :magazines do |f| %>   

    <div class="field">
      <%= form.label :magazines %>
      <%= form.collection_check_boxes(:magazine_ids, 
                                      Magazine.all,
                                      :id,
                                      :name) do |b| %>
        <%= b.label class:"label-checkbox" do %>
          <%= b.check_box + b.text%>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= form.fields_for :enologist_magazines do |f| %>

    <div class="field">
      <%= form.label :editor %>
      <%= form.check_box :editor %>
    </div>  

     <div class="field">
      <%= form.label :writer %>
      <%= form.check_box :writer %>
    </div> 

     <div class="field">
      <%= form.label :reviewer %>
      <%= form.check_box :reviewer %>
    </div>  

  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to "Wines", root_path %>
<%= link_to "Magazines",  magazines_path %>

app/views/enologists/edit.html.erb
<h1>Editing Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Show', @enologist %> |
<%= link_to 'Back', enologists_path %>

app/views/enologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologists</h1>

<table>
  <thead>
    <tr>
      <th>Nº</th>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Magazine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologists.each do |enologist| %>
      <tr>
        <td><%= enologist.id %></td>
        <td><%= enologist.name %></td>
        <td><%= enologist.age %></td>
        <td><%= enologist.nationality %></td>
        <td><%= sort_magazines enologist.enologist_magazines %></td>
        <td><%= link_to 'Show', enologist %></td>
        <td><%= link_to 'Edit', edit_enologist_path(enologist) %></td>
        <td><%= link_to 'Destroy', enologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologist', new_enologist_path %>
<%= link_to 'Wines', root_path %>
<%= link_to "Magazines",  magazines_path %>

app/views/enologists/new.html.erb
<h1>New Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Back', enologists_path %>

app/views/enologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @enologist.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @enologist.nationality %>
</p>

<%= link_to 'Edit', edit_enologist_path(@enologist) %> |
<%= link_to 'Back', enologists_path %>
<%= link_to "Magazines",  magazines_path %>