config/routes.rb
Rails.application.routes.draw do
  resources :enologist_magazines
  resources :magazines
  resources :enologists
  devise_for :users
  resources :strains
  resources :wines
  resources :enologist_wines
  

  root to: 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enologist_wine.rb
class EnologistWine < ApplicationRecord
  belongs_to :enologist
  belongs_to :wine
  
end

app/controllers/enologist_wines_controller.rb
class EnologistWinesController < ApplicationController
  before_action :set_enologist_wine, only: %i[ show edit update destroy ]

  # GET /enologist_wines or /enologist_wines.json
  def index
    @enologist_wines = EnologistWine.all
  end

  # GET /enologist_wines/1 or /enologist_wines/1.json
  def show
  end

  # GET /enologist_wines/new
  def new
    @enologist_wine = EnologistWine.new
    @wines = Wine.all.pluck(:name, :id)
    @enologists = Enologist.all.pluck(:name, :id)
  end

  # GET /enologist_wines/1/edit
  def edit
  end

  # POST /enologist_wines or /enologist_wines.json
  def create
    @enologist_wine = EnologistWine.new(enologist_wine_params)

    respond_to do |format|
      if @enologist_wine.save
        format.html { redirect_to @enologist_wine, notice: "Enologist wine was successfully created." }
        format.json { render :show, status: :created, location: @enologist_wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enologist_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologist_wines/1 or /enologist_wines/1.json
  def update
    respond_to do |format|
      if @enologist_wine.update(enologist_wine_params)
        format.html { redirect_to @enologist_wine, notice: "Enologist wine was successfully updated." }
        format.json { render :show, status: :ok, location: @enologist_wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enologist_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologist_wines/1 or /enologist_wines/1.json
  def destroy
    @enologist_wine.destroy
    respond_to do |format|
      format.html { redirect_to enologist_wines_url, notice: "Enologist wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist_wine
      @enologist_wine = EnologistWine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_wine_params
      params.require(:enologist_wine).permit(:score, :wine_id, :enologist_id )
    end
end

app/helpers/enologist_wines_helper.rb
module EnologistWinesHelper
end

app/views/enologist_wines/_form.html.erb
<%= form_with(model: enologist_wine) do |form| %>
  <% if enologist_wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist_wine.errors.count, "error") %> prohibited this enologist_wine from being saved:</h2>

      <ul>
        <% enologist_wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>


  <div class="field">
    <%= form.label :wine_id %>
    <%= form.select :wine_id, @wines %>
  </div>

  <div class="field">
    <%= form.label :enologist_id %>
    <%= form.select :enologist_id, @enologists %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enologist_wines/edit.html.erb
<h1>Editing Enologist Wine</h1>

<%= render 'form', enologist_wine: @enologist_wine %>

<%= link_to 'Show', @enologist_wine %> |
<%= link_to 'Back', enologist_wines_path %>

app/views/enologist_wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologist Wines</h1>

<table>
  <thead>
    <tr>
        <th>Score</th>
        <th>Wine</th>
        <th>Enologist</th>
        <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologist_wines.each do |enologist_wine| %>
      <tr>
        <td><%= enologist_wine.score  %></td>
        <td><%= enologist_wine.wine.name  %></td>
        <td><%= enologist_wine.enologist.name  %></td>
        <td><%= link_to 'Show', enologist_wine %></td>
        <td><%= link_to 'Edit', edit_enologist_wine_path(enologist_wine) %></td>
        <td><%= link_to 'Destroy', enologist_wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologist Wine', new_enologist_wine_path %>
<%= link_to 'Wines', wines_path %>

app/views/enologist_wines/new.html.erb
<h1>New Enologist Wine</h1>

<%= render 'form', enologist_wine: @enologist_wine %>

<%= link_to 'Back', enologist_wines_path %>

app/views/enologist_wines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enologist_wine_path(@enologist_wine) %> |
<%= link_to 'Back', enologist_wines_path %>