config/routes.rb
Rails.application.routes.draw do
  resources :enologist_magazines
  resources :magazines
  resources :enologists
  devise_for :users
  resources :strains
  resources :wines
  resources :enologist_wines
  

  root to: 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains, dependent: :destroy

    has_many :enologist_wines
    has_many :enologists, through: :enologist_wines, dependent: :destroy

    validates :name, presence: true

    accepts_nested_attributes_for :wine_strains, reject_if: ->(attributes){ attributes['strain_id'].blank? || attributes['percentage'].blank? }
    accepts_nested_attributes_for :enologist_wines, reject_if: ->(attributes){attributes['enologist_id'].blank? || attributes ['score'].blank?}
    
    def to_s
        score
    end
    
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /wines or /wines.json
  def index
    @wines = Wine.all
    
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  
  # GET /wines/new
  def new
    @wine = Wine.new
    @strains = Strain.available.pluck(:name, :id)  #repasar, los botones de build, es para dar mas de una seleccion
    3.times {@wine.wine_strains.build}
    # @wine.wine_strains.build
    # @wine.wine_strains.build
    # @wine.wine_strains.build

    @enologists = Enologist.order('age DESC').pluck(:name, :id)
    1.times {@wine.enologist_wines.build}
    
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.available.pluck(:name, :id)  #repasar, los botones de build, es para dar mas de una seleccion
    3.times { @wine.wine_strains.build }  
    @enologists = Enologist.order('age DESC').pluck(:name, :id)

    #para que aparesca el score en edit
    @wine.enologist_wines.build
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, wine_strains_attributes: [:id, :strain_id, :percentage, :_destroy], enologist_wines_attributes: [:id, :enologist_id, :score, :_destroy], enologist: [:name, :age, :natioanlity])
    end
end

app/helpers/wines_helper.rb
module WinesHelper
    def sort_strains(wine_strains)
        wine_strains.map { |ws| [ws.strain.name, ws.percentage]}
                    .map {|ws| "#{ws.first} (#{ws.second}%)"}
                    .sort
                    .join( ', ')  
    end
    

    def sort_enologist(wine_enologists)
        wine_enologists.map {|wo| "#{wo.enologist.name} (#{wo.score}%)"}.sort.join(', ')
    end
end

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.fields_for :wine_strains do |f| %>

    <div class= "field">
      <%= f.label :strain_id %>
      <%= f.select :strain_id, @strains, prompt: "Selecciona una alternativa" %> 
    </div>    

    <div class= "field">
      <%= f.label :percentage %>
      <%= f.number_field :percentage %> 
    </div> 

  <% end %>

  <%= form.fields_for :enologist_wines do |f| %>

    <div class= "field">
      <%= f.label :enologist %>
      <%= f.select :enologist_id, @enologists %> 
      <%= f.label :score %>
      <%= f.number_field :score %> 
    </div> 

  <% end %>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_score.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.fields_for :enologist_wines do |f| %>

      <div class= "field">
        <%= f.label :score %>
        <%= f.number_field :score %> 
      </div> 
    
  <% end %>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'layouts/login' %>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Strains</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.id %></td>
        <td><%= wine.name %></td>
        <td><%= sort_strains wine.wine_strains %></td>
        <td><%= sort_enologist wine.enologist_wines %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Score', new_enologist_wine_path %>                    
        
        <% if current_user.admin?  %>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin?  %>
  <%= link_to 'New Wine', new_wine_path %>
  <%= link_to 'Enologists', enologists_path %>
<% end %>
<%= link_to 'Strains', strains_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.enologist_wines.map(&:score) %>
</p>


<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>